### ISSUE TITLE
Hypothetical  neurotoxicity issue??

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Series-1-Fenarimols#12]
In reference to the series 3 phenothiazine mycetoma work (that being antifungal compounds derived from psychiatric drugs) @bendndi brought up an important but overlooked by all of us rule: 

> it’s a bad idea (if not a killer) to have brain exposure in a compound with no need for brain penetration. Too risky, and brain biochemistry is too capricious to risk messing with it for no reason.

**This got me thinking - how likely are the planar and somewhat oily series one compounds to enter the brain and possibly interfere with neurosteroid synthesis?** 

Using some freely available BBB  prediction tools it appears one or more of our series 1 leads can easily cross the BBB:

![bbbpredict](https://user-images.githubusercontent.com/3164942/52451682-febed800-2b0d-11e9-8464-84c8fc8e931f.png)

![bbb2](https://user-images.githubusercontent.com/3164942/52451886-d5eb1280-2b0e-11e9-8310-b8b20e329573.png)

I feel this should be looked into further but I am not aware of what experimental resources we have to prove/disprove this prediction @mattodd

**Comment by bendndi** [comment]
@MFernflower  

Personally I wouldn't put any faith at all in any kind of "current state of the art" _in silico_ BBB prediction, in my experience of both trying to breed out BBB penetration for systemic projects and breed in BBB penetration for CNS projects, these algorithms are (at best) close to random. Occasionally you may see one which matches up with experimental observations _within a chemical series_, but I'd not use it to classify a diverse set of compounds. 

My recommendation for the experimental validation of the BBB prediction would be brain exposure PK;   for the PgP substrate prediction (which I also have little faith in) we could check MDR1-MDCK / CACO2 permeability. None of these are cheap unfortunately...

My previous comment on S3 was linked directly to the idea of repurposing or using as discovery starting point a known "promiscuous" antipsychotic (the list of known CNS targets for chlorpromazine is enormous). I think it is either a no go (repurposing) or overly challenging (as a starting point).
I think this question l is not of fundamental importance for S1 until it has been shown to be an issue (e.g by in vivo B/P ratio or major CNS off target flags).

**Comment by MFernflower** [comment]
@bendndi More than likely S3 will be shelved because of too many unknowns (photosensitivity, possible CNS off target effects) 

@mattodd Do you agree to this? 

What got me thinking after your concerns for S3 was that S1 drugs inhibit steroid synthesis and if they cross into the brain could hypothetically interfere with brain steroid synthesis causing idiosyncratic events

**Comment by MFernflower** [comment]
@bendndi @mattodd Do you think it would be wise to get a NOAEL determination done in rats for a few of the S1 compounds?

**Comment by bendndi** [comment]
@MFernflower @mattodd I think we are at way too early a stage with any of the series to start looking at NOAEL. That's something I'd reserve for candidate molecule(s), and we're still a long way from that (to be brutally honest). 
Let's concentrate on getting a lead first (activity in a rodent model).

**Comment by bendndi** [comment]
My advice if we're concerned about possible toxic effects would be to run a "simple" tolerability study prior to any rodent model - basically mimic the dosing regimen in healthy animals first, and check cageside behaviour and necropsy for any abnormalities. This is actually a prerequisite for new series at DNDi prior to moving into rodent infection models. We have an established process at one of our Toxicology CROs in which we _may_ be able to piggy back a single compound from MycetOs for relatively low cost, however we'd need to actually have an identified potential lead compound first - not there yet. @mattodd @MFernflower
