### ISSUE TITLE
An interesting idea

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Series-1-Fenarimols#15]
Seeing the bicyclic system that was used in https://github.com/OpenSourceMalaria/Series4/issues/71 got me thinking:

![bicyc](https://user-images.githubusercontent.com/3164942/61422900-b9cc7800-a8db-11e9-9a2d-07b48d237dc9.png)

InChI=1S/C19H25F2N3O2/c1-2-26-17(25)24-8-6-23(7-9-24)15(14-4-3-5-22-10-14)18-11-19(12-18,13-18)16(20)21/h3-5,10,15-16H,2,6-9,11-13H2,1H3

 SCYWWIINNKLBEF-UHFFFAOYSA-N 

FC(C12CC(C1)(C2)C(N2CCN(CC2)C(=O)OCC)C=2C=NC=CC2)F

http://molview.org/?q=FC(C12CC(C1)(C2)C(N2CCN(CC2)C(=O)OCC)C=2C=NC=CC2)F

**Comment by MFernflower** [comment]
@edwintse @fantasy121 do we have anymore BCP-OH to oxidize to aldehyde?

**Comment by fantasy121** [comment]
@MFernflower I think @edwintse would be able to better answer this question as I am unfamiliar with this synthesis route.

**Comment by MFernflower** [comment]
on hold for now will repon later point
