### ISSUE TITLE
Possible screen against Balamuthia????

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Series-1-Fenarimols#17]
### **Update: Dennis Kyle of the University of Georgia is able to screen against all three genera of neurotrophic amoebas so might be of more value should we proceed further with this avenue.** 

http://outbreaknewstoday.com/naegleria-fowleri-drug-research-with-dennis-kyle-phd-64534/

CYP51 (the target of the fenarimol drug class) does exist in slime molds (E.G Dictyostelium) and in human pathogenic _Balamuthia_ relative _Acanthamoeba castellanii_

https://www.uniprot.org/uniprot/Q1ZXH9

https://www.nature.com/articles/s41598-017-07495-z 

<strike> Joseph DeRisi has papers relating to drug screening methods against a slime-mold-like single-celled extremely virulent neuropathogen known as _Balamuthia mandrillaris_

Perhaps it could be worthwhile to send some good preforming compounds against _Madurella mycetomatis_ to him to assay vs _Balamuthia_? (Both organisms have an extremely thick wall but balamuthia's wall is made of cellulose <strike>or chitosan</strike> not chitin) </strike>

**Comment by MFernflower** [comment]
Thoughts on this @mattodd - Currently only one drug known to kill Balamuthia - Nitroxoline

Obligtory video of these things eating cells - From DeRisi lab https://www.youtube.com/watch?v=B-GfKM759p0

**Comment by fantasy121** [comment]
@MFernflower I think that's a good idea. Perhaps we can choose from our current pool of candidates or wait for the next round of biological evaluation when more compounds are synthesised.

**Comment by MFernflower** [comment]
@fantasy121 We could perhaps send two compounds that did poorly and two that did great against _Madurella mycetomatis in vivo_ to him - provided we have enough for him to run it in triplicate

**Comment by MFernflower** [comment]
Of-course there's no guarantee of potency vs _Balamuthia_ as it's cell wall is made of cellulose rather than the chitin wall of _Madurella_

**Comment by MFernflower** [comment]
@wwjvdsande Ever heard of this organism?

**Comment by wwjvdsande** [comment]
No I did not hear of this organisms, but we can always try.

**Comment by MFernflower** [comment]
@wwjvdsande One of the more rare infections out there - Again it's more closely related to slime mold than to actual fungi but as you know, mycology traditionally included study of the slime molds!

**Comment by wwjvdsande** [comment]
That's true, furthermore the CYP51 target was not only found in fungi

**Comment by MFernflower** [comment]
@mattodd Would it be possible to contact JDR regarding if we can send two actives and two inactives for screening vs BAM?

**Comment by MFernflower** [comment]
@mattodd Would it be possible to contact JDR regarding if we can send two active molecules and two inactive ones for screening vs BAM? @fantasy121 @wwjvdsande

**Comment by MFernflower** [comment]
@fantasy121 @mattodd Update: Dennis Kyle of the University of Georgia is able to screen against all three genera of neurotrophic amoebas so might be of more value should we proceed further with this.

**Comment by MFernflower** [comment]
@mattodd Does Denis Kyle use github?

**Comment by MFernflower** [comment]
Going to re-open this issue with more precise information
