### ISSUE TITLE
[Molecule idea] Expanded heme binding motif 

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Series-1-Fenarimols#19]
A random shower thought got me to think about what would happen if we had expanded the heme binding motif from one aromatic ring to a bicyclic aromatic system?

I propose an analogue of EPL-BS0495:

Thoughts everyone? @mattodd @dmitrij176 

![quin](https://user-images.githubusercontent.com/3164942/69514428-471e7980-0f19-11ea-8ab5-237f18a069e3.png)

Needed precursor: http://www.matrixscientific.com/127564.html  10 grams for under 40 USD

```

InChI=1S/C23H23ClFN3O2/c1-2-30-23(29)28-11-9-27(10-12-28)22(19-8-7-18(24)14-20(19)25)17-13-16-5-3-4-6-21(16)26-15-17/h3-8,13-15,22H,2,9-12H2,1H3

PCAUGHBSHJKAOO-UHFFFAOYSA-N 


ClC1=CC(=C(C=C1)C(N1CCN(CC1)C(=O)OCC)C=1C=NC2=CC=CC=C2C1)F

Swiss ADME cLogP: 4.17

```

**Comment by dmitrij176** [comment]
Interesting idea. @MFernflower is it a novel or a known molecule?
Also, how does the incorporation of a bicyclic ring system will affect compound solubility?
It will probably be less soluble, no?

**Comment by MFernflower** [comment]
This novel compound is more of a SAR probe than anything else - the only
clogp package I have access to reported around 4.5 @dmitrij176

Could you run the molecule through something like StarDrop?

>

**Comment by MFernflower** [comment]
Big thanks to the University of Washington for making this molecule!!!!!!!!!!!!!!!!!!

**Comment by fantasy121** [comment]
That is an interesting molecule idea. Love your random shower thoughts @MFernflower
