### ISSUE TITLE
LogD values

### ISSUE THREAD

**Issue by rosalynclz** [OpenSourceMycetoma/Series-1-Fenarimols#22]
Hi all, I'm Rosalyn, a MPharm student at UCL currently doing a research on the relevance of LogD to the in vivo potency of compounds against eumycetoma. My aim is to compile all the LogD pH7.4 values and plot a graph of in vivo potency against LogD to determine their correlation as the preliminary results published indicated that compounds with lower lipophilicity showed better in vivo potency.

I am aware of the existence of the Google [spreadsheet](https://docs.google.com/spreadsheets/d/1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80/edit#gid=954203120) for all the compounds but I would like to ask if there are any other molecules beyond this [paper](https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0006437) that were tested in vivo? Once I have the values, I will need the logD values to be calculated, if you wouldn't mind @bendndi ?

**Comment by rosalynclz** [comment]
In my process of compiling the data values for LogD and in vivo % survival and wanting to cross-check those in the Master List and the [article](https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0006437#pntd-0006437-g010), I noticed that there are no specific LogD data values stated in the text, supplementary documents or graph context in Figure 10 (page 17) for me to include them in the spreadsheet. @wwjvdsande May I know where I can obtain these LogD values as the [image file ](https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0006437#pntd-0006437-g010) of the graph has no data labels (x,y) and one can only visually estimate them from the image? 
@fantasy121 May I know where you got the logD values from for your Figure 13(page 45) of your thesis?

**Comment by rosalynclz** [comment]
I have compiled the % survival values of _M.mycetomatis_-infected larvae into the [Master List as a separate sheet](https://docs.google.com/spreadsheets/d/1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80/edit#gid=1872217356) and am awaiting a reply from @bendndi to help out with the generation of their pH7.4 LogD values. 
So far, I have only found 16 compounds with in vivo % survival values, @wwjvdsande are there any other compounds that have been tested in the larvae model that I may have missed?

**Comment by wwjvdsande** [comment]
@rosalynclz sorry there is no new data yet. Hopefully we will have some before the end of the larvae season but otherwise it will be next larvae season (in the spring). We have tested the toxicity of the in vitro active compounds in the last weeks and luckily did not find any toxicity. We are hopefully doing the first screenings this week and next week, however the weather has already changed here. This means that the larvae quality will become less. It could mean that we have to stop after this week if the controls are dying as well.

**Comment by wwjvdsande** [comment]
@rosalynclz i don't know if it will help but we tested in the past terbinafin, amphotericin B (the classical one, not the liposomal ones) and several azoles for efficacy in the larval model. They were not all active. Terbinafin showed activity and amphotericin b showed activity but most of the azoles did not at the concentration tested. So that might be helpful as well. PMID: 28992315

**Comment by bendndi** [comment]
@rosalynclz Updated master sheet with LogD from Stardrop

**Comment by rosalynclz** [comment]
@bendndi Thank you for your help. Would you mind generating LogD values for a couple more molecules in the [sheet](https://docs.google.com/spreadsheets/d/1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80/edit#gid=1872217356)?

**Comment by rosalynclz** [comment]
@bendndi Thank you for your help. Would you mind generating LogD values for a couple more molecules in the [sheet](https://docs.google.com/spreadsheets/d/1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80/edit#gid=1872217356)?

**Comment by wwjvdsande** [comment]
@rosalynclz not a problem. I will try to do that today.

**Comment by MFernflower** [comment]
Nice graphs

**Comment by bendndi** [comment]
@rosalynclz I updated the[ master sheet](https://docs.google.com/spreadsheets/d/1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80/edit#gid=1872217356) with Stardrop LogDs - note however that it is not really that relevant to compare *calculated* LogDs across different chemotypes - withi a particular chemotype the relative rank ordering of calculated logD is usuall yvery good, but they are notoriously unrelaiable when comparing across different chemical series.

**Comment by wwjvdsande** [comment]
@rosalynclz I checked the survival percentages in the raw data for these graphs:
AMB: 23.26%
TBF: 20.45%
VCZ: 11.11%
ITZ: 6.67%
KTZ: 6.67%
PCZ: 4.44%

These survival curves were generated on human pharmacokinetic equivalent dosages, unlike in mycetOS were we used a fixed amount. For PCZ for instance, the dosage used here was roughly half of what was used in the MycetOS experiment. This also explains why in this paper we did not find enhanced survival for PCZ while in mycetOS we did.

**Comment by MFernflower** [comment]
@wwjvdsande im just curious - what is the dosage of posaconazole needed to
kill the mold in vitro?

**Comment by mattodd** [comment]
I finally uploaded Rosalyn Chan's very nice thesis that includes all this work - sorry for the delay and thanks to all those generous souls who helped Rosalyn with her calculations and ideas. The thesis is [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/blob/master/Theses%20Reports%20Docs/Rosalyn%20Chan%20UCL%202020/Rosalyn%20Chan%20MPharm%20Thesis%20UCL%20Pharmacy%202020.pdf) with a CC-BY licence. I'll close this issue and install a link to it on the wiki at https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/wiki/Current-Targets-and-Activities so this discussion is not lost - there are some original things in the above we may not have captured in the wiki yet.
