### ISSUE TITLE
Molecule size & effects on grain penetration

### ISSUE THREAD

**Issue by rosalynclz** [OpenSourceMycetoma/Series-1-Fenarimols#24]
Below is the data on molecular weight and polar surface area of 19 [compounds ](https://docs.google.com/spreadsheets/d/1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80/edit#gid=518064767)tested in the in vivo larvae model. (Data on PSA were obtained from ChemSpider ACD predictions).
![image](https://user-images.githubusercontent.com/56122898/68874948-efeafe80-06f9-11ea-828e-38794a729d26.png)
Graph of in vivo efficacy vs molecular weight:
![image](https://user-images.githubusercontent.com/56122898/68875069-1f017000-06fa-11ea-8558-254a1cac79e5.png)
Graph of in vivo efficacy vs PSA:
![image](https://user-images.githubusercontent.com/56122898/68876932-20806780-06fd-11ea-9a0f-7c92dd82cacc.png)

Would @bendndi and @edwintse mind suggesting some methods/software to calculate the approximate size/diameter of the compounds above as I am interested in studying the effect of size of compounds on their in vivo efficacy and would like to plot a graph of those variables to determine if there is a size exclusion barrier cut-off points for the grains?

**Comment by mattodd** [comment]
Nice analysis. Looks like logD more important factor than MW, PSA. Are we overlooking anything?

On Thu., 14 Nov. 2019, 16:37 rosalynclz, <notifications@github.com<mailto:notifications@github.com>> wrote:

Below is the data on molecular weight and polar surface area of 19 compounds <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1YhK-3i2KwuVabo1GbZSgVjAUbavEICCMKi5v-EhNq80%2Fedit%23gid%3D518064767&data=02%7C01%7C%7C9b5707dd1cdb4de23cd108d76920e78b%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637093462350511358&sdata=WUfmn0CRz6BvwDmkz1Quyh1kRCigCuXrnbH6vh4Ic7k%3D&reserved=0> tested in the in vivo larvae model. (Data on PSA were obtained from ChemSpider ACD predictions).
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F56122898%2F68874948-efeafe80-06f9-11ea-828e-38794a729d26.png&data=02%7C01%7C%7C9b5707dd1cdb4de23cd108d76920e78b%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637093462350511358&sdata=6Sgy4CFYzUuc1f7ksBAzcR9nNqD%2BvQ7xbUrrQgZrhKY%3D&reserved=0>
Graph of in vivo efficacy vs molecular weight:
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F56122898%2F68875069-1f017000-06fa-11ea-8558-254a1cac79e5.png&data=02%7C01%7C%7C9b5707dd1cdb4de23cd108d76920e78b%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637093462350521351&sdata=HbBQdhzrJGsUJSQULvfZqiNjj%2FmLstEQQyRU2IkyHK0%3D&reserved=0>
Graph of in vivo efficacy vs PSA:
[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F56122898%2F68875990-a56a8180-06fb-11ea-842e-4f5cbdbca42d.png&data=02%7C01%7C%7C9b5707dd1cdb4de23cd108d76920e78b%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637093462350521351&sdata=fQnUG1dSB4uYQ%2B5IafEVCDD9%2FILozienAn3HMzy%2BzCs%3D&reserved=0>

Would @bendndi<https://github.com/bendndi> and @edwintse<https://github.com/edwintse> mind suggesting some methods/software to calculate the approximate size/diameter of the compounds above as I am interested in studying the effect of size of compounds on their in vivo efficacy and would like to plot a graph of those variables to determine if there is a size exclusion barrier cut-off points for the grains?

**Comment by MFernflower** [comment]
Following with interest

**Comment by mattodd** [comment]
Just pinging @bendndi and @edwintse on this in case they have any chance to look at ways to calculate approximate size/diameter of the compounds above, or indeed anyone else with a preferred method? I know the answer depends on the question you ask, but something that allows a reasonably uncontroversial assessment of *size*?

**Comment by bendndi** [comment]
@rosalynclz @mattodd  One thing that could be interesting to check would be Principal Moments of Inertia PMI plot, which is more linked to shape than size. See [here ](https://llama.leeds.ac.uk/help.php#in-depth-pmi) You would have to plot by PMI and then colour by in vivo activity to check any link

A simpler alternative to this which could be analysed in same way as the MW / LogD is  molecular shape index available in datawarrior(could also look at molecular flexibility too):

![image](https://user-images.githubusercontent.com/36627399/70628074-bab5cb80-1c27-11ea-80e6-29bf56e56916.png)

There may be some other descriptors available via RDKit but I'm not sure how "simple" these would be to implement.

**Comment by rosalynclz** [comment]
@bendndi Thank you for the reply. Would looking at total surface area (Data warrior) and molecular volume ([Molinspiration](https://www.molinspiration.com/services/volume.html)) and calculating the TSA:MV ratio be a suitable size approximator?

**Comment by bendndi** [comment]
@rosalynclz I guess you could look at the molecular volume alone, and also the TSA:MV - could be interesting.

**Comment by mattodd** [comment]
I finally uploaded Rosalyn Chan's very nice thesis that includes all this work - sorry for the delay and thanks to all those generous souls who helped Rosalyn with her calculations and ideas. The thesis is [here](https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/blob/master/Theses%20Reports%20Docs/Rosalyn%20Chan%20UCL%202020/Rosalyn%20Chan%20MPharm%20Thesis%20UCL%20Pharmacy%202020.pdf) with a CC-BY licence. I'll close this issue and install a link to it on the wiki at https://github.com/OpenSourceMycetoma/Series-1-Fenarimols/wiki/Current-Targets-and-Activities so this discussion is not lost.
