### ISSUE TITLE
Possible pathogenic free-living amoebae (PFLA) screen? 

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Series-1-Fenarimols#25]
**Update 12.8.19 - A twitter conversation has been started with Dr.Kyle https://twitter.com/parasite_doc/status/1203686245353869312**

It has recently came to my attention that Dr.Dennis Kyle from the University of Georgia (United States)
is able to screen against what are termed pathogenic free-living amoebae or PFLA's - A small group of protozoa with some slightly fungus-like features and a high mortality rate should they enter the CNS.

He recently published a paper showing that posaconazole is able to kill the causative agent of the most common PFLA CNS infection - Naegleria 

https://www.ncbi.nlm.nih.gov/pubmed/30358879

I find this interesting as we have all found that the same drug has shown some promise in eumycetoma and that the original fenarimol derivatives were intended for Chagas disease - itself caused by a relative of Naegleria 

I propose we send two active and two inactive piperazine compounds for a full PFLA screen and follow this up in the future with two active and two inactive non-piperazine compounds!

**(this is an updated repost of the previous issue regarding PFLA screening)**

**Comment by MFernflower** [comment]
@mattodd If any of our compounds show good activity vs PFLA'S we might be able to secure some funding from organizations like http://www.jordansmelskifoundation.org/ to move the whole of the fenarimol section of OSMYC forward

**Comment by MFernflower** [comment]
@mattodd Just curious if any updates on this

**Comment by MFernflower** [comment]
@mattodd @dmitrij176 @fantasy121 This was brought up at meeting and is pending further action

**Comment by MFernflower** [comment]
Talked about at latest meeting #28

**Comment by MFernflower** [comment]
@fantasy121 @mattodd to decide and send 8 compounds - 4 that were not effective against mycetoma 4 that were

**Comment by MFernflower** [comment]
@fantasy121 @mattodd Dr.Kyle said 15 mg of each of the 8 compounds (4 active potent against MM 4 not active at all) is good

**Comment by mattodd** [comment]
OK, so we're talking about confirmed actives and 4 not. Obviously costs are lower if we ship from one place. But can @dmitrij176 and @fantasy121 please comment on compounds that are available in lab that could be shipped? Either made, or bought. Any Epichem compounds will likely not be available unless we ship from them directly, which would be a separate conversation with @bendndi . 15 mg of each is actually quite a lot. I've just emailed Dennis to check this, and to check on any shipping requirements.

**Comment by MFernflower** [comment]
I raise a glass to you all for getting this running! 15 mg might have been
an overshoot on my part!

>

**Comment by dmitrij176** [comment]
@MFernflower @mattodd if we are talking specifically about compounds with piperazine moiety, then from my library I can send two positive controls (DM4-3B and DM16-1) together with DM18-2 analog. 
But DM18-2 activity status is yet unknown. It still requires biological evaluation.
In terms of available product mass, out of these 3 molecules, I think only DM16-1 is out of stock. There is definitely plenty of other 2 even for 15 mg batches.

**Comment by MFernflower** [comment]
The two positive controls would make up 2 of the four actives @dmitrij176
@mattodd

**Comment by dmitrij176** [comment]
@MFernflower exactly. We just need to decide whether to synthesise more DM16-1. Unless @fantasy121 has other positive on offer.

**Comment by MFernflower** [comment]
Keep me posted everyone! @dmitrij176 @fantasy121

**Comment by MFernflower** [comment]
@dmitrij176 @fantasy121 really any two that do well in MM can be sent as our "positive control"

**Comment by MFernflower** [comment]
![drkyle](https://user-images.githubusercontent.com/3164942/82001370-0c281380-9629-11ea-8b6a-ae2684437aef.png)

**Comment by fantasy121** [comment]
I can put together 2 potent and two non-potent compounds from my collection. Can't promise they'll be 15 mg as I don't think I have enough for all four. Around 3–5mg each is more feasible

**Comment by MFernflower** [comment]
15 mg might have been an overshot on my part @mattodd @fantasy121

**Comment by MFernflower** [comment]
@fantasy121 I overestimated everything - might be a good idea to send 2 vials of each compound (1 and 10 micromolar in DMSO) - should not need too much dry material to make those

**Comment by MFernflower** [comment]
@fantasy121 @bendndi @wwjvdsande  @mattodd https://www.biorxiv.org/content/10.1101/2020.05.14.096776v1.full.pdf - Interesting new pre-print from Kyle lab - CYP51 inhibitors best on N. Fowleri and A. castellanii


Will be interesting to see if that trend continues with our fenarimol compounds!!!

**Comment by MFernflower** [comment]
Down the line when screening data is produced (few months eta perhaps?) can @cdsouthan push it out to public databases

**Comment by MFernflower** [comment]
Closing as @MOUSEY007 Will create main issue when compounds are in mail or received
