### ISSUE TITLE
Finalizing the amoeba screen  [PLEASE SEE UPDATE]

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Series-1-Fenarimols#30]
This is a continuation of #25 in order to organize what needs to be done:

**What we need:**  2 active (most potent on hand) and 2 inactive mycetoma compounds - 4 milligrams of each

 **What the problem is:**  All the physically made mycetoma compounds reside in either Australia or the United Kingdom - shipping is expensive so we need to be able to ship the 4 compounds from one location only!

**What has to be done:** The UCL @dmitrij176 and USYD @fantasy121 teams need to each search their compound libraries to see if they have enough materials to fulfill the needs above - the school that has all four compounds sends the package to Dr.Kyle in the United States. (due to the pandemic, this might be delayed for some time)

We also need to check with Dr.Kyle about shipping information.

**What the end goal is:**  Get the four compounds and their activities pushed to a public database @cdsouthan can work his magic

_Perhaps write a very short paper?_

**Comment by MFernflower** [comment]
Please note that the solution is 10 millimolar not 10 micromolar  @fantasy121 @dmitrij176

**Comment by MFernflower** [comment]
@fantasy121 Perhaps we could use some of the first paper actives - for the 500 microliter (we could lower the volume down perhaps ask dr.kyle) of 10 millimolar stock we would only need sub 5 milligrams of each compound 

![actives](https://user-images.githubusercontent.com/3164942/86198198-1349a900-bb25-11ea-816e-381309e6d292.png)

**Comment by MFernflower** [comment]
@fantasy121 @dmitrij176 Update: 4 mg of compound is more than enough for the screens

**Comment by fantasy121** [comment]
![20200706Amoeba Screening](https://user-images.githubusercontent.com/36176821/86587216-8f803880-bfcc-11ea-865d-ab07c7b97703.jpg)
I'm planning to send these four to have screened against amoeba. The 2 actives I've recently confirmed to still be viable. Cetirizine is a commercial product so it should be still viable. The second inactive is pending re-characterisation to confirm it hasn't degraded over time so that might change. @MFernflower @mattodd @dmitrij176

**Comment by fantasy121** [comment]
> ![20200706Amoeba Screening](https://user-images.githubusercontent.com/36176821/86587481-04ec0900-bfcd-11ea-989e-fe18cf8abdf6.jpg)
> 
> I'm planning to send these four to have screened against amoeba. The 2 actives I've recently confirmed to still be viable. Cetirizine is a commercial product so it should be still viable. The second inactive is pending re-characterisation to confirm it hasn't degraded over time so that might change. @MFernflower @mattodd @dmitrij176

**Comment by MFernflower** [comment]
@fantasy121 this is amazing news!

**Comment by MFernflower** [comment]
@fantasy121 Might not be a bad idea to also post a public facing email to the twitter thread

**Comment by MFernflower** [comment]
@fantasy121 Since twitter seems to be a dead end at the moment - might be able to reach via email? https://cellbio.uga.edu/directory/people/dennis-kyle 

Also email more likely to be looked at using your email and credentials since I do not have a proper professional email yet

**Comment by fantasy121** [comment]
> @fantasy121 Since twitter seems to be a dead end at the moment - might be able to reach via email? https://cellbio.uga.edu/directory/people/dennis-kyle
> 
> Also email more likely to be looked at using your email and credentials since I do not have a proper professional email yet

I'm gathering the molecules today. So after I can confirm I have all four, I will look into sending Kyle an email. Can you send me the link to the twitter post as well? I can retweet and make a comment.

**Comment by MFernflower** [comment]
@fantasy121 You are tagged on twitter!!!

**Comment by fantasy121** [comment]
> @fantasy121 You are tagged on twitter!!!

Yep saw it now. Will retweet. The old notification was burried under a bunch of other things. Thank you

**Comment by MFernflower** [comment]
Yeah, Twitter isn't the best when it comes to organization

**Comment by MFernflower** [comment]
@fantasy121 Still radio silence on twitter - have you send email or are going to wait a few days???

**Comment by MFernflower** [comment]
@fantasy121 Contact christopher.rice@uga.edu to exchange shipping info

**Comment by mattodd** [comment]
Hi - just catching up on the thread and movements. Sounds really great. So @fantasy121 you have samples of those four compounds, and they're still OK by NMR, and you're happy to ship? We don't need to re-make? And as I understand it, we have a contact willing to receive compounds in the Kyle lab? In short, we're good to go here, is that right?

**Comment by MFernflower** [comment]
@fantasy121 Any update on ameba screen shipment? I just saw that you are currently in quarantine but still curious nonetheless

**Comment by MFernflower** [comment]
Dr.Rice should be contacting you soon for shipping info @mattodd @fantasy121

**Comment by MOUSEY007** [comment]
Hi all, 
Just wanted to make my presence known! 
Looking forward to screening the compounds and sharing the results! 
- Chris Rice.

**Comment by mattodd** [comment]
Welcome aboard @MOUSEY007 ! I'll add you as a member of MycetOS so that you can do more things here.

**Comment by MFernflower** [comment]
@fantasy121 @mattodd Github checklist has been updated

**Comment by fantasy121** [comment]
Update: I've confirmed that the four compounds above are still viable so I will be preparing for shipment to Dr. Kyle's team in a few days.

**Comment by MFernflower** [comment]
@fantasy121 How long is shipping from AUS to US? 

@MOUSEY007 when will PFLA's be fully grown up?

**Comment by MOUSEY007** [comment]
@MFernflower they will be fully confluent for passage on Friday and be ready next Wed/Thurs to be ready for screening whenever the drugs arrive 👍.

**Comment by fantasy121** [comment]
Not sure how long shipping will take as I haven't done one to the US before, plus with the COVID situation there could be delay. But shipping will be via FedEx so it shouldn't take too long

**Comment by MFernflower** [comment]
Horray for FedEx!

**Comment by MFernflower** [comment]
Closing this - can @MOUSEY007 open an issue for the receipt and eventual results provided by these compounds - perhaps if your willing to add a short into about PFLA's for the rest of our team?

**Comment by MOUSEY007** [comment]
Yes, I will confirm receipt, screen with biological repeats ~3 week turn around and provide the results against all 3 pathogenic amoebae in table format with IC50s +/- standard deviation and a little background or supply links to papers for this info that I've previously written. I will also supply the raw data and plate maps for anyone who wishes to re-analyse the data set I obtain. 
I'll be back in touch with all the data hopefully sometime soon!

**Comment by MFernflower** [comment]
Compounds have been selected - new issue to be opened when compounds are in mail or have been received

**Comment by MFernflower** [comment]
@MOUSEY007 Sounds like a solid plan of action - @fantasy121 can you open a new issue when compounds are in the mail?
