### ISSUE TITLE
Logo for MycetOS

### ISSUE THREAD

**Issue by fantasy121** [OpenSourceMycetoma/Series-1-Fenarimols#33]
I will be presenting for the E$$ENTIAL MEDINCE$ project as part of the Breaking Good team for The Australian National Science Week 2020. I will be mentioning/promoting MycetOS in my talk and was wondering if I can have a larger resolution image of our logo as the ones I can find on Google is a bit pixelated. Does anyone have a larger of the MycetOS logo?

**Comment by mattodd** [comment]
https://github.com/OpenSourceMycetoma/Talks-Meetings-Publicity/tree/master/Online%20Graphics?

**Comment by fantasy121** [comment]
Thanks Mat

**Comment by MFernflower** [comment]
Closing this - i guess it's fixed?? @fantasy121

**Comment by mattodd** [comment]
Yes, can close, but the question itself raises the question of whether our documentation is sufficient. The Talks-Meetings-Publicity repo is meant for Mycetos-wide items like this, and maybe we need to make that clearer somewhere.
