### ISSUE TITLE
We need a simple Newsletter Signups page - any volunteers?

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMycetoma/Series-1-Fenarimols#42]
If we want to disseminate activity in MycetOS, it might be a good idea to use occasional newsletters. We found over in Open Source Antibiotics (opensourceantibiotics/Series-2-Diarylimidazoles#34) that these can easily be constructed collaboratively in a GitHub issue, then copied and pasted into an email and sent out. It's easier to construct the newsletter that way, rather than on something like Mailchimp.

For GDPR reasons we need people to agree to receive these newsletters, i.e. a sign-up page. [We have one @Danaklug made for OSA](https://docs.google.com/forms/d/e/1FAIpQLSf4UieL5pRQqN5rOL4q-t57qcpJhHG_jqMXV774FPUJBmnBbQ/viewform), and need one for MycetOS.

The list of people on the distribution list needs to be managed somehow. The easiest way to achieve this would be to use a Google sheet associated with the existing opensourcemycetoma@gmail.com account (@fantasy121 and I can provide access to this, I think).

**REQUEST**: Would anyone like to set up the Google form for sign-up (complete with MycetOS logo, and the same questions as for the OSA form), and ensure that the sign-up works, in that it collects the email addresses to a sheet we can use for the newsletter? I would argue that all contributors to MycetOS on Github can be added automatically...

@fantasy121 @dmitrij176 @kym834 @Wilson-Lm 

It would be very good to use this sign-up in our newsletter that can go out on World NTD Day on Jan 30th as per #41.

**Comment by kym834** [comment]
Sign up form and linked google sheet are now complete. Had to play with the logo a little as it only allowed for horizontal images. Please let me know if this OK. Here is the [form](https://forms.gle/hHvURWKJQTymhJ9p7).

**Comment by mattodd** [comment]
Great work @kym834! Closing this issue since I've installed a link to the signup at https://github.com/OpenSourceMycetoma/General-Start-Here/blob/master/README.md and on the Tech-ops wiki at https://github.com/OpenSourceMycetoma/MycetOS-Tech-Ops/wiki/Newsletters
