### ISSUE TITLE
Came across a very interesting molecule today

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Series-1-Fenarimols#9]
https://pubchem.ncbi.nlm.nih.gov/compound/ancymidol

Would it be possible to get samples of this molecule and get them screened against Mycetoma and/or cryptococcus?

**Comment by mattodowd25** [comment]
@MFernflower That compound is already in the library as EPL-BS0052. Was this the reasoning behind suggesting the molecule? I noticed it has the pyrimidine substructure. Exploring the extent to which this affects the compound may be of interest to the project.

**Comment by MFernflower** [comment]
Indeed! I assume the pyrimidine interacts with the iron atom in the heme center of CYP51
